movie_site/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('movies/', views.MoviesView.as_view(), name='movies'),
    path('movie/<slug:slug>/', views.MovieDetailView.as_view(), name="movie_detail"),
    path('accounts/login/', views.login_page, name='login_page'),
    path('accounts/register/', views.register_page, name="register_page"),
]

movie_site/movie_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_site/main/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default="")
    url = models.SlugField(max_length=160, unique=True, default="")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class Actor(models.Model):
    """ Actors and Directors """
    name = models.CharField(max_length=200)
    year = models.PositiveSmallIntegerField(default=0)
    description = models.TextField(default="")
    image = models.ImageField(upload_to="actors/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Actors and directors"
        verbose_name_plural = "Actors and directors"


class Genre(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default="")
    url = models.SlugField(max_length=160, unique=True, default="")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Genre"
        verbose_name_plural = "Genres"


class Movie(models.Model):
    title = models.CharField(max_length=20)
    slogan = models.CharField(max_length=200, default='')
    description = models.TextField(default="")
    poster = models.ImageField(default=None, upload_to='movies/')
    country = models.CharField(max_length=100, default="")
    directors = models.ManyToManyField(Actor, verbose_name="director", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="actors", related_name="film_actor")
    genre = models.ManyToManyField(Genre)
    world_premiere = models.PositiveIntegerField(default=0)
    budget = models.PositiveIntegerField(default=0)
    worldwide = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(Category, verbose_name="Category", on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=130, unique=True, default="")
    draft = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={"slug": self.url})

    """
    def save(self, *args, **kwargs):
        value = self.title
        self.url = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)
    """

    class Meta:
        verbose_name = "Movie"
        verbose_name_plural = "Movies"


class MovieShots(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(default="")
    image = models.ImageField(upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Movie", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Movie shot"
        verbose_name_plural = "Movie shots"


class RatingStar(models.Model):
    value = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = "Rating star"
        verbose_name_plural = "Rating stars"


class Rating(models.Model):
    ip = models.CharField(max_length=15)
    star = models.ForeignKey(RatingStar, verbose_name="star", on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, verbose_name="movie", on_delete=models.CharField)

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Rating"
        verbose_name_plural = "Ratings"


class Review(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=50, default="USER")
    parent = models.ForeignKey('self', verbose_name="Parent", blank=True, null=True, on_delete=models.SET_NULL)
    movie = models.ForeignKey(Movie, verbose_name="movie", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = "Reviews"

movie_site/main/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', ]

movie_site/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Movie
from .forms import CreateUserForm

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


def home(request):
    return render(request, 'main/home.html')


def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or password is incorrect')

    context = {}
    return render(request, 'main/login_page.html', context)


def register_page(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            form.save()
            return redirect('login_page')

    context = {'form': form}
    return render(request, 'main/register_page.html', context)


class MoviesView(ListView):
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = 'main/movies.html'


class MovieDetailView(DetailView):
    model = Movie
    slug_field = "url"
    template_name = 'main/movie.html'

movie_site/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    {% endblock head %}
    <title>Shmetflix</title>
</head>
<body>
    {% include 'main/navbar.html' %}

    {% block content %}

    {% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

movie_site/main/templates/main/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="{% static 'main/css/home.css'%}" type="text/css">
    <title>Shmetflix</title>
</head>
<body>
    <!--  Header  -->
    <header class="header">
        <div class="container">
            <div class="header__inner">
                <div class="header__logo">
                    <img height="75" width="155" src="static/main/images/shmetflix_logo.png" alt="logo">
                </div>
                <nav class="nav">
                    <a class="button" href="/movies">Sign in</a>
                </nav>
            </div>
        </div>
    </header>

    <!--  Intro  -->
    <div class="intro">
        <div class="container">
            <div class="intro__inner">
                <div class="intro__title">
                    <h1 class="intro__h1">Unlimited movies, TV <br>shows, and more.</h1>
                    <h2 class="intro__h2">Watch anywhere. Cancel anytime.</h2>
                    <h3 class="intro__h3">Ready to watch? Enter your email to create or restart your membership.</h3>
                </div>
            </div>
        </div>
    </div>

    <!--  Features  -->
    <div class="feature1">
        <div class="features_container">
            <div class="watchOnTv">
                <h1 class="watchOnTv__title">
                    Enjoy on your TV.
                </h1>
                <h2 class="watchOnTv__subtitle">
                    Watch on Smart TVs, Playstation, Xbox,<br>Chromecast, Apple TV, Blu-ray players,
                    and<br>more.
                </h2>
            </div>
        </div>
    </div>

    <div class="feature2">
        <div class="features_container">
            <div class="downloadAndWatch">
                <h1 class="downloadAndWatch__title">
                    Download your shows<br>to watch offline.
                </h1>
                <h2 class="downloadAndWatch__subtitle">
                    Save your favorites easily and always have<br>something to watch.
                </h2>
            </div>
        </div>
    </div>

    <div class="feature3">
        <div class="features_container">
            <div class="watchOnDevice">
                <h1 class="watchOnDevice__title">
                    Watch everywhere.
                </h1>
                <h2 class="watchOnDevice__subtitle">
                    Stream unlimited movies and TV shows<br>on your phone, tablet, laptop, and TV<br>without paying more.
                </h2>
            </div>
        </div>
    </div>

    <div class="feature4">
        <div class="features_container">
            <div class="kidsValueProp">
                <h1 class="kidsValueProp__title">
                    Create profiles for kids.
                </h1>
                <h2 class="kidsValueProp__subtitle">
                   Send kids on adventures with their<br>favorite characters in a space made just<br>for them—free with your membership.
                </h2>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <div class="footer__inner">
                <div class="footer__block">
                    <h4 class="footer__title">Location</h4>
                    <address class="footer__address">
                        <div>38 E. Devonshire St.Canonsburg, PA 15317</div>
                        <div>5 Richardson Street Glen Ellyn, IL 60137</div>
                        <div>18 Addison Lane Whitestone, NY 11357</div>
                    </address>
                </div>
                <div class="footer__block">
                    <h4 class="footer__title">Our social media</h4>
                    <div class="social">
                        <div class="social_item">
                            <a class="social__icon" target="_blank" href="https://www.facebook.com"><img weight="30" height="30"
                                                                                         src="static/main/images/social_icons/facebook.png" alt=""></a>
                            <a class="social__icon" target="_blank" href="https://twitter.com"><img class="middle_img" weight="30" height="30"
                                                                                    src="static/main/images/social_icons/twitter.png" alt=""></a>
                            <a class="social__icon" target="_blank" href="https://www.instagram.com"><img weight="30" height="30"
                                                                                           src="static/main/images/social_icons/instagram.png" alt=""></a>
                        </div>
                    </div>
                </div>
                <div class="footer__block">
                    <h4 class="footer__title">About Shmetflix</h4>
                    <div class="footer__text">
                        <p>
                            Shmetflix is a large international company.The company was founded in 3021 by DennKK
                        </p>
                    </div>
                </div>
            </div><!-- /.footer__inner -->
        </div> <!-- /.container -->

        <div class="copyright">
            <div class="container">
                <div class="copyright__text">
                    <div>Copyright © 2021 Shmetflix. All Rights Reserved</div>
                    <div>
                        Made <a target="_blank" class="copyright__link" href="https://github.com/DennKK">by DennKK</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>

movie_site/main/templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="{% static 'main/css/home.css'%}" type="text/css">
    <title>Shmetflix</title>
</head>
<body>
    <!--  Header  -->
    <header class="header">
        <div class="container">
            <div class="header__inner">
                <div class="header__logo">
                    <img height="75" width="155" src="static/main/images/shmetflix_logo.png" alt="logo">
                </div>
                <nav class="nav">
                    <a class="button" href="/movies">Sign in</a>
                </nav>
            </div>
        </div>
    </header>

    <!--  Intro  -->
    <div class="intro">
        <div class="container">
            <div class="intro__inner">
                <div class="intro__title">
                    <h1 class="intro__h1">Unlimited movies, TV <br>shows, and more.</h1>
                    <h2 class="intro__h2">Watch anywhere. Cancel anytime.</h2>
                    <h3 class="intro__h3">Ready to watch? Enter your email to create or restart your membership.</h3>
                </div>
            </div>
        </div>
    </div>

    <!--  Features  -->
    <div class="feature1">
        <div class="features_container">
            <div class="watchOnTv">
                <h1 class="watchOnTv__title">
                    Enjoy on your TV.
                </h1>
                <h2 class="watchOnTv__subtitle">
                    Watch on Smart TVs, Playstation, Xbox,<br>Chromecast, Apple TV, Blu-ray players,
                    and<br>more.
                </h2>
            </div>
        </div>
    </div>

    <div class="feature2">
        <div class="features_container">
            <div class="downloadAndWatch">
                <h1 class="downloadAndWatch__title">
                    Download your shows<br>to watch offline.
                </h1>
                <h2 class="downloadAndWatch__subtitle">
                    Save your favorites easily and always have<br>something to watch.
                </h2>
            </div>
        </div>
    </div>

    <div class="feature3">
        <div class="features_container">
            <div class="watchOnDevice">
                <h1 class="watchOnDevice__title">
                    Watch everywhere.
                </h1>
                <h2 class="watchOnDevice__subtitle">
                    Stream unlimited movies and TV shows<br>on your phone, tablet, laptop, and TV<br>without paying more.
                </h2>
            </div>
        </div>
    </div>

    <div class="feature4">
        <div class="features_container">
            <div class="kidsValueProp">
                <h1 class="kidsValueProp__title">
                    Create profiles for kids.
                </h1>
                <h2 class="kidsValueProp__subtitle">
                   Send kids on adventures with their<br>favorite characters in a space made just<br>for them—free with your membership.
                </h2>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <div class="footer__inner">
                <div class="footer__block">
                    <h4 class="footer__title">Location</h4>
                    <address class="footer__address">
                        <div>38 E. Devonshire St.Canonsburg, PA 15317</div>
                        <div>5 Richardson Street Glen Ellyn, IL 60137</div>
                        <div>18 Addison Lane Whitestone, NY 11357</div>
                    </address>
                </div>
                <div class="footer__block">
                    <h4 class="footer__title">Our social media</h4>
                    <div class="social">
                        <div class="social_item">
                            <a class="social__icon" target="_blank" href="https://www.facebook.com"><img weight="30" height="30"
                                                                                         src="static/main/images/social_icons/facebook.png" alt=""></a>
                            <a class="social__icon" target="_blank" href="https://twitter.com"><img class="middle_img" weight="30" height="30"
                                                                                    src="static/main/images/social_icons/twitter.png" alt=""></a>
                            <a class="social__icon" target="_blank" href="https://www.instagram.com"><img weight="30" height="30"
                                                                                           src="static/main/images/social_icons/instagram.png" alt=""></a>
                        </div>
                    </div>
                </div>
                <div class="footer__block">
                    <h4 class="footer__title">About Shmetflix</h4>
                    <div class="footer__text">
                        <p>
                            Shmetflix is a large international company.The company was founded in 3021 by DennKK
                        </p>
                    </div>
                </div>
            </div><!-- /.footer__inner -->
        </div> <!-- /.container -->

        <div class="copyright">
            <div class="container">
                <div class="copyright__text">
                    <div>Copyright © 2021 Shmetflix. All Rights Reserved</div>
                    <div>
                        Made <a target="_blank" class="copyright__link" href="https://github.com/DennKK">by DennKK</a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>

movie_site/main/templates/main/login_page.html
<!DOCTYPE html>
{% extends 'main/base.html' %}
{% load static %}
<html>
<head>
{% block head %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'main/css/login.css' %}" type="text/css">
{% endblock head %}
</head>
<body>
	{% block content %}

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>
				</div>

				<div class="card_bottom">
					{% for message in messages %}
						<p id="messages">{{ message }}</p>
					{% endfor %}

					{{ form.errors }}

					<div class="mt-4">
						<div class="d-flex justify-content-center links">
							Don't have an account? <a href="{% url 'register_page' %}" class="ml-2">Sign Up</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% endblock content %}
</body>

</html>

movie_site/main/templates/main/movie.html
<!DOCTYPE html>
<html lang="en">
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/main.css'%}" type="text/css">
    <title>Shmetflix</title>
</head>
<body>
    <div class="movie">
        <div class="movie__inner">
            <h1 class="movie__name">{{ movie }}</h1>
            <div class="movie__description">{{ movie.description }}</div>
            <div class="movie__directors">
                {% for directors in movie.directors.all %}
                    <div class="directors__name">Directors: {{ directors.name }}</div>
                {% endfor %}
            </div>
            <div class="movie__actors">
                Actors:
                {% for actors in movie.actors.all %}
                    <div class="actor__name">{{ actors.name }}</div>
                {% endfor %}
            </div>
            <div class="movie__genres">
                Genres:
                {% for genres in movie.genre.all %}
                    <span class="genre__name">{{ genres.name }}</span>
                {% endfor %}
            </div>
            <div class="movie__premiere">World premiere: {{ movie.world_premiere }}</div>
            <div class="movie__country">Countries: {{ movie.country }}</div>
            <div class="movie__budget">Budget: {{ movie.budget }}</div>
            <div class="movie__worldwide">Box office: {{ movie.worldwide }}</div>
        </div>
    </div>
</body>
</html>

movie_site/main/templates/main/movies.html
{% extends 'main/base.html' %}
{% load static %}
<html lang="en">
<head>
{% block head %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/css/movies.css'%}" type="text/css">
{% endblock head %}
<body>
    {% block content %}

    <!-- Movies --->
        <div class="row row-cols-6 row-cols-md-4 g-4">
            {% for movie in movie_list %}
              <div class="col">
                <div class="card h-100 text-light">
                    <img class="card-img-top" width="50" height="300" src="{{ movie.poster.url }}">
                  <div class="card-body">
                    <h5 class="card-title">{{ movie.title|truncatechars:30 }}</h5>
                    <p class="card-text">{{ movie.description|truncatechars:100 }}</p>
                  </div>
                  <div class="card-footer">
                    <a href="{{ movie.get_absolute_url }}">Learn more</a>
                  </div>
                </div>
              </div>
            {% endfor %}
        </div>

    {% endblock content %}
</body>

movie_site/main/templates/main/navbar.html
{% load static %}
<style>
    .navbar {
        background-color: #000
    }
</style>
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <img class="navbar-brand" height="55" width="125" src="{% static 'main\images\shmetflix_logo.png' %}" alt="logo">
        <div class="btn-group dropstart">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Menu
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'movies' %}">Movies</a></li>
            <li><a class="dropdown-item" href="#">Home</a></li>
            <li><a class="dropdown-item" href="{% url 'login_page' %}">login</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'register_page' %}">Register</a></li>
          </ul>
        </div>
    </div>
</nav>

movie_site/main/templates/main/register_page.html
<!DOCTYPE html>
{% extends 'main/base.html' %}
{% load static %}
<html>
<head>
{% block head %}
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'main/css/register.css' %}" type="text/css">
{% endblock head %}
</head>
<body>
	{% block content %}

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				<div class="card_bottom">
					{{ form.errors }}

					<div class="mt-4">
						<div class="d-flex justify-content-center links">
							Already have an account? <a href="{% url 'login_page' %}" class="ml-2">Login</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>

	{% endblock content %}
</body>
</html>